version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: telebot
      POSTGRES_USER: tat
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    env_file:
      - .env
    container_name: bot_container  # Добавляем явное имя контейнера
    depends_on:
      - db

volumes:
  postgres_data:
